### ISSUE TITLE
virus in file

### ISSUE THREAD

**Issue by GroGaloraGran** [CowCoding0/Gartic-Phone-Draw-Bot#6]
Hello
in you file virustotal find some virus
https://www.virustotal.com/gui/file/0faddbf09db2c91e8a9b399557c16f4c2429f5025e559a6ed06f933869a89445

**Comment by CowCoding0** [comment]
Honestly don't know what half that stuff is. If there is a virus then it would be from pyinstaller which I used to package it. If you don't want to use the exes, use the py files and if you read through them you'd see there is no malicious code. There is no virus.
